export {default as Home} from './Home'
export {default as FoodDetail} from './FoodDetail'
export {default as AllFoods} from './AllFoods'
export {default as Cart} from './Cart'
export {default as Checkout} from './Checkout'
export {default as Orders} from './Orders'